### ISSUE TITLE
[Bot Issue] Channels with emotes are no longer loaded upon first initialization of the bot

### ISSUE THREAD

**Issue by lifehackerhansol** [nh-server/Kurisu#1009]
**Issue Description**

This likely will not affect Kurisu in the long run, as the database is already initialized exactly to NH's spec. For anyone who gets the server template to test the bot, Kurisu does not recognize any channels with emotes in its name such as elsewhere or appeals.

This used to work in previous commits.

Startup log (my naming scheme is lame): 
![image](https://user-images.githubusercontent.com/37358975/133292612-9a188693-ad14-4887-9a72-80d236cbc99a.png)

Traceback: 
```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/kurisu/cogs/logs.py", line 39, in on_ready
    - React permissions in {self.bot.channels['off-topic'].mention}, {self.bot.channels['elsewhere'].mention}, and {self.bot.channels['nintendo-discussion'].mention}.
AttributeError: 'NoneType' object has no attribute 'mention'
```

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/kurisu/cogs/rules.py", line 23, in on_ready
    await self.init_rules()
  File "/home/kurisu/cogs/rules.py", line 73, in init_rules
    self.extra = f"""While we appreciate everyone who boosts the server **IT DOES NOT MAKE YOU EXEMPT FROM THE RULES.** We've given booster reaction perms in {self.bot.channels['off-topic'].mention}, {self.bot.channels['elsewhere'].mention}, and {self.bot.channels['nintendo-discussion'].mention}, you can also stream in the Streaming gamer voice channel, and change your nick once every 6hrs using a bot command in your DM with {self.bot.guild.me.mention},  as a thank you for boosting the server.
AttributeError: 'NoneType' object has no attribute 'mention'
```

**Comment by FrozenChen** [comment]
People shouldnt have this issue with the server template given in the README, except for the streaming gamer channel which needs a fix since its not a text channel and its retrieved by name currently
